use SuperLiga;
select nombre, capacidad from estadios;
select nombre, nacionalidad from jugadores where posicion = "Delantero";
select * from jugadores where valor > 50000000 and peso < 80;
select * from partidos where goles_local > 2 or goles_visitante < 1;
select nombre, valor, nacionalidad from jugadores order by valor desc;
select count(*) as "Nº Jugadores", id_club as "Equipo" from jugadores group by id_club;
select id_club as "Equipo", sum(valor) as "Valor toral" from jugadores group by id_club;
select id_club as "Equipo", avg(altura) as "Altura promedio" from jugadores group by id_club;
select * from club;
select id, ValorTotal from club where ValorTotal > 800000000;
select id_club as "Equipo", sum(valor) as "Valor toral" from jugadores group by id_club having sum(valor) > 800000000;
select nacionalidad from jugadores group by nacionalidad;
select distinct nacionalidad from jugadores;
select nombre, valor,(valor+valor*0.1) as "Valor +10%" from jugadores;
select nombre, altura as "Altura(m)", peso as "Peso(kg)" from jugadores;
select nombre, FechaNacimiento from jugadores where FechaNacimiento between "1990-01-01" and "2000-12-31";
select nombre, nacionalidad from jugadores where nombre like "J%";
select nacionalidad,count(*) from jugadores group by nacionalidad;
select nacionalidad,count(*) from jugadores group by nacionalidad having count(*) > 10;
select * from jugadores where nacionalidad in ("España","Argentina");
select sum(goles_local+goles_visitante) as "Goles temporada" from partidos where temporada = 1;